#!/usr/bin/env python
import os
import jinja2
import webapp2


template_dir = os.path.join(os.path.dirname(__file__), "templates")
jinja_env = jinja2.Environment(loader=jinja2.FileSystemLoader(template_dir), autoescape=False)


class BaseHandler(webapp2.RequestHandler):

    def write(self, *a, **kw):
        return self.response.out.write(*a, **kw)

    def render_str(self, template, **params):
        t = jinja_env.get_template(template)
        return t.render(params)

    def render(self, template, **kw):
        return self.write(self.render_str(template, **kw))

    def render_template(self, view_filename, params=None):
        if not params:
            params = {}
        template = jinja_env.get_template(view_filename)
        return self.response.out.write(template.render(params))


class MainHandler(BaseHandler):
    def get(self):
        return self.render_template("index.html")
class AboutHandler(BaseHandler):
    def get(self):
        return self.render_template("about.html")

class UganiHandler(BaseHandler):
    def get(self):
        return self.render_template("ugani.html")


    def post(self):
        stevilo1=self.request.get("stevilo")
        stevilo1=int(stevilo1)
        rezultat=""
        stevilo2=56
        pravilno="Cestitamo, uganili ste pravo stevilko"
        nepravilno="Zal vec srece prihodnjic. Napisana stevilka ni prava"


        if stevilo1 == stevilo2:
            rezultat=pravilno
        else:
            rezultat=nepravilno

        spremenljivke={
            "stevilo1":stevilo1,
            "stevilo2":stevilo2,
            "rezultat":rezultat,
            "pravilno":pravilno,
            "nepravilno":nepravilno
            }
        return self.render_template("ugani.html",params=spremenljivke)






app = webapp2.WSGIApplication([
    webapp2.Route('/', MainHandler),
    webapp2.Route('/o-meni', AboutHandler),
    webapp2.Route('/ugani', UganiHandler)
], debug=True)
